const countries = {
  shu: {
    logo: "./img/shu.jpg",
    officers: [
      "baosanniang",
      "fazheng",
      "guanping",
      "guansuo",
      "guanxing",
      "guanyinping",
      "guanyu",
      "huangzhong",
      "jiangwei",
      "liubei",
      "liushan",
      "machao",
      "madai",
      "pangtong",
      "weiyan",
      "xingcai",
      "xushu",
      "yueying",
      "zhangbao",
      "zhangfei",
      "zhaoyun",
      "zhoucang",
      "zhugeliang",
    ],
  },
  wei: {
    logo: "./img/wei.jpg",
    officers: [
      "caiwenji",
      "caocao",
      "caopi",
      "caoren",
      "caoxiu",
      "dianwei",
      "guojia",
      "jiaxu",
      "lidian",
      "manchong",
      "pangde",
      "wangyi",
      "xiahoudun",
      "xiahouyuan",
      "xuhuang",
      "xuzhu",
      "xunyou",
      "xunyu",
      "yujin",
      "yuejin",
      "zhanghe",
      "zhangliao",
      "zhenji",
    ],
  },
  wu: {
    logo: "./img/wu.jpg",
    officers: [
      "chengpu",
      "daqiao",
      "dingfeng",
      "ganning",
      "handang",
      "huanggai",
      "lianshi",
      "lingtong",
      "lumeng",
      "lusu",
      "luxun",
      "sunce",
      "sunjian",
      "sunquan",
      "sunshangxiang",
      "taishici",
      "xiaoqiao",
      "xusheng",
      "zhoutai",
      "zhouyu",
      "zhuran",
    ],
  },
};
