const countries = {
  shu: {
    logo: "./img/shu.jpg",
    officers: [
      "baosanniang",
      "fazheng",
      "guanping",
      "guansuo",
      "guanxing",
      "guanyinping",
      "guanyu",
      "huangzhong",
      "jiangwei",
      "liubei",
      "liushan",
      "machao",
      "madai",
      "pangtong",
      "weiyan",
      "xingcai",
      "xushu",
      "yueying",
      "zhangbao",
      "zhangfei",
      "zhaoyun",
      "zhoucang",
      "zhugeliang",
    ],
  },
  wei: {
    logo: "./img/wei.jpg",
  },
  wu: {
    logo: "./img/wu.jpg",
  },
};
